# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
    boot = {
      loader = {
        grub = {
          enable = true;
          efiSupport = true;
          device = "nodev";
        };
        efi.canTouchEfiVariables = true;
      };
      initrd = {
        availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
        luks.devices."luks-58bea4a7-73e9-455f-ae6c-53a7c2188190".device = "/dev/disk/by-uuid/58bea4a7-73e9-455f-ae6c-53a7c2188190";

      };

      kernelModules = [ "kvm-intel" "samsung-galaxybook" ];

    };
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57fc17b6-e21b-4e81-bb4a-23dcf2517df5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2213b53b-6020-47c9-8e56-ad288ee16271".device = "/dev/disk/by-uuid/2213b53b-6020-47c9-8e56-ad288ee16271";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A46A-54FA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/078becc4-2d2c-4c9a-9e92-63ab4dcc4d85"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
